#!/usr/bin/env bash
#
# start torrent bot

start() {
repository="TeleTor"
path=$(pwd)

if [[ -f ${path}/teletor.py ]]
then
    run_bot
else
    echo "Can't find teletor.py"
fi
}

run_bot() {
    (nohup python ${path}/teletor.py &)
}

start
